### ISSUE TITLE
Problem using the module twice in a project

### ISSUE THREAD

**Issue by kief** [infrablocks/terraform-aws-base-networking#3]
I'm trying to create two instances of the base networking in a single Terraform project. To be fair, I'm doing this to demonstrate why this is a Bad Idea. Nevertheless, it probably ought to work.

I'm getting an error about the provider; this might suggest that the module should not define a provider, as per [the tf module docs](https://www.terraform.io/docs/modules/usage.html#providers-within-modules):

> While in principle provider blocks can appear in any module, it is recommended that they be placed only in the root module of a configuration

My project has two module declarations, one like this:
```
module "prod-base-network" {
  source  = "infrablocks/base-networking/aws"
  ...
```
The other being named `stage-base-network`.

The error I get when I run `terraform plan` is:
```
Error: Error asking for user input: 1 error(s) occurred:

* module.base-network.aws_nat_gateway.base: configuration for module.base-network.provider.aws is not present; a provider configuration block is required for all operations
```

The tf documentation above sounds like it might be best to remove the `provider.tf` from the module source. I suspect that will have knock-on effects on building and testing the module, which I've so far avoided diving into.

**Comment by tobyclemson** [comment]
Hi @kief,

Thanks for the report, the change to module provider hierarchy was introduced in a recent version of terraform and I'm yet to update the infrablocks modules.

I'll aim take a look at this today and get a new release out.

Thanks,
Toby

**Comment by tobyclemson** [comment]
Hi @kief,

Please try version 0.1.23 and see if that solves the problem.

Thanks,
Toby

**Comment by kief** [comment]
```
Error: Error asking for user input: 1 error(s) occurred:

* module.base-network.aws_route53_zone_association.base: configuration for module.base-network.provider.aws is not present; a provider configuration block is required for all operations
```

**Comment by tobyclemson** [comment]
Strange, my tests are passing with a simple provider configuration in the root module of:

```
provider "aws" {
  region = "${var.region}"
  version = "1.2"
}
```

See [the test configuration](spec/infra/harness) for an example of using the module that currently works.

What version of terraform are you using? Is this a public repo I can take a look at?

Toby

**Comment by tobyclemson** [comment]
To confirm, tests are running fine without the pinned provider version.

**Comment by kief** [comment]
Thanks @tobyclemson. Seems to be working now, the problem was I had existing infrastructure using just the one module. Once I destroyed it I was able to plan and create.
