### ISSUE TITLE
Conflict with private zone association

### ISSUE THREAD

**Issue by kief** [infrablocks/terraform-aws-base-networking#4]
I've got a project using `terraform-aws-dns-zones`  as well as `terraform-aws-base-networking`, and I'm getting this error:

```
* module.base-network.aws_route53_zone_association.base: 1 error(s) occurred:

* aws_route53_zone_association.base: ConflictingDomainExists: The VPC that you chose, vpc-6705bd01 in region eu-west-1, is already associated with another private hosted zone that has an overlapping name space, default.private.cloudspin.net..
	status code: 400, request id: e156c4f4-2843-11e8-bfa5-7966af78f306
```

I believe this is because the association between the dns zone and the vpc is effectively being declared twice: once when the zone is created in `terraform-aws-dns-zones` , and then again with a zone association statement in `terraform-aws-base-networking`

My code to use the dns module (0.1.7) is:
```
module "dns-zones" {
  source = "infrablocks/dns-zones/aws"
  version = "~> 0.1"

  domain_name             = "${var.public_domain_name}"
  private_domain_name     = "${var.private_domain_name}"

  private_zone_vpc_region = "${var.region}"
  private_zone_vpc_id     = "${module.base-network.vpc_id}"
}
```

My code to use the networking module (0.1.24) is:

```
module "base-network" {
  source  = "infrablocks/base-networking/aws"
  version = "~> 0.1"
  
  vpc_cidr = "10.1.0.0/16"
  region = "${var.region}"

  availability_zones = "${var.availability_zones}"
  
  component = "${var.component_base}-${var.env_name}"
  deployment_identifier = "${var.env_name}"
  include_lifecycle_events = "no"
  
  private_zone_id = "${module.dns-zones.private_zone_id}"
}
```

Looking at the source for the modules, in the dns module I see:

```
resource "aws_route53_zone" "private_zone" {
  name = "${var.private_domain_name}"
  vpc_id = "${var.private_zone_vpc_id}"
  vpc_region = "${var.private_zone_vpc_region}"
}
```

and in the networking module I see:
```
resource "aws_route53_zone_association" "base" {
  zone_id = "${var.private_zone_id}"
  vpc_id = "${aws_vpc.base.id}"
}
```

These look like they're trying to set the same thing.

The [terraform docs](https://www.terraform.io/docs/providers/aws/r/route53_zone_association.html) imply that `aws_route53_zone_association` is not meant to declare the same vpc-id:

```
resource "aws_route53_zone" "example" {
  name   = "example.com"
  vpc_id = "${aws_vpc.primary.id}"
}

resource "aws_route53_zone_association" "secondary" {
  zone_id = "${aws_route53_zone.example.zone_id}"
  vpc_id  = "${aws_vpc.secondary.id}"
}
```

How are you using this? I don't see a workaround unless I create the private zone for a different vpc?

**Comment by tobyclemson** [comment]
The challenge here is that when creating a private hosted zone, you need to specify a VPC to associate. However, it's a bit chicken and egg because you typically want to create the zone before creating any of the networks that are associated to it.

Typically, I specify the default VPC for that region during zone creation and then allow the base networking module to associate subsequently created VPCs.

However, this is a bit of a security issue since you're likely not to want the default VPC to have access to your zone. I haven't yet thought of a good workaround for this and it hasn't really caused any problem as I typically never touch the default VPC.

**Comment by tobyclemson** [comment]
Hey @kief, are you happy with me closing this? I think things are working as intended and will add the above description to the docs when they get written.
