### ISSUE TITLE
include_nat_gateway as a variable name in 2.3.0

### ISSUE THREAD

**Issue by stephaneclavel** [infrablocks/terraform-aws-base-networking#7]
Hello

I think module version 2.3.0 uses include_nat_gateway as a variable name while readme and TF registry mention include_nat_gateway**s**. 

[steph@centos7-2 MyFirstVPC]$ ti -upgrade
Upgrading modules...
Downloading infrablocks/base-networking/aws 2.3.0 for base-network...
- base-network in .terraform/modules/base-network

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/aws versions matching "~> 3.0"...
- Installing hashicorp/aws v3.23.0...
- Installed hashicorp/aws v3.23.0 (signed by HashiCorp)

[steph@centos7-2 MyFirstVPC]$ tv

Error: Unsupported argument

  on vpc.tf line 30, in module "base-network":
  30:   include_nat_gateways = "no"

An argument named "include_nat_gateways" is not expected here. Did you mean
"include_nat_gateway"?

[steph@centos7-2 MyFirstVPC]$ grep -r "include_nat_gateway" .
./.terraform/modules/base-network/config/roles/harness.yaml:  include_nat_gateway: "%{hiera('include_nat_gateway')}"
./.terraform/modules/base-network/config/defaults.yaml:include_nat_gateway: "yes"
./.terraform/modules/base-network/spec/infra/harness/main.tf:  include_nat_gateway = var.include_nat_gateway
./.terraform/modules/base-network/spec/infra/harness/variables.tf:variable "include_nat_gateway" {}
./.terraform/modules/base-network/spec/nat_spec.rb:  context 'when include_nat_gateway is no' do
./.terraform/modules/base-network/spec/nat_spec.rb:      reprovision(include_nat_gateway: "no")
./.terraform/modules/base-network/spec/nat_spec.rb:  context 'when include_nat_gateway is yes' do
./.terraform/modules/base-network/spec/nat_spec.rb:      reprovision(include_nat_gateway: "yes")
./.terraform/modules/base-network/README.md:| include_nat_gateway              | Whether or not to deploy a NAT gateway for outbound Internet connectivity | true    | yes                                         |
./.terraform/modules/base-network/nat.tf:  count = var.include_nat_gateway == "yes" ? 1 : 0
./.terraform/modules/base-network/nat.tf:  count = var.include_nat_gateway == "yes" ? 1 : 0
./.terraform/modules/base-network/private_subnets.tf:  count = var.include_nat_gateway == "yes" ? 1 : 0
./.terraform/modules/base-network/variables.tf:variable "include_nat_gateway" {
./vpc.tf:  include_nat_gateway = "no"
[steph@centos7-2 MyFirstVPC]$ grep -r "include_nat_gateways" .
[steph@centos7-2 MyFirstVPC]$

**Comment by jonassvalin** [comment]
This has been resolved with release [3.0.0](https://registry.terraform.io/modules/infrablocks/base-networking/aws/3.0.0), thanks!
